/*
 * generated by Xtext
 */
package org.xtext.hipie.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.hipie.ui.internal.HIPIEActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class HIPIEExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return HIPIEActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return HIPIEActivator.getInstance().getInjector(HIPIEActivator.ORG_XTEXT_HIPIE_HIPIE);
	}
	
}
