/*
 * generated by Xtext
 */
package org.xtext.hipie;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class HIPIERuntimeModule extends org.xtext.hipie.AbstractHIPIERuntimeModule {

}
