/**
 * generated by Xtext
 */
package org.xtext.hipie.ui.contentassist;

import org.xtext.hipie.ui.contentassist.AbstractHIPIEProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class HIPIEProposalProvider extends AbstractHIPIEProposalProvider {
}
