/*
 * generated by Xtext
 */
package org.xtext.hipie.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class HIPIEUiModule extends org.xtext.hipie.ui.AbstractHIPIEUiModule {
	public HIPIEUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
