/**
 * generated by Xtext
 */
package org.xtext.hipie.validation;

import org.xtext.hipie.validation.AbstractHIPIEValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class HIPIEValidator extends AbstractHIPIEValidator {
}
