/*
 * generated by Xtext
 */
package org.xtext.hipie;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class HIPIEUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return org.xtext.hipie.ui.internal.HIPIEActivator.getInstance().getInjector("org.xtext.hipie.HIPIE");
	}
	
}
