/*
 * generated by Xtext
 */
package org.xtext.hipie.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.xtext.hipie.services.HIPIEGrammarAccess;

public class HIPIEParser extends AbstractContentAssistParser {
	
	@Inject
	private HIPIEGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.xtext.hipie.ui.contentassist.antlr.internal.InternalHIPIEParser createParser() {
		org.xtext.hipie.ui.contentassist.antlr.internal.InternalHIPIEParser result = new org.xtext.hipie.ui.contentassist.antlr.internal.InternalHIPIEParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getBasePropAccess().getAlternatives(), "rule__BaseProp__Alternatives");
					put(grammarAccess.getBasePropAccess().getAlternatives_0_0(), "rule__BaseProp__Alternatives_0_0");
					put(grammarAccess.getCategoryTypeAccess().getAlternatives(), "rule__CategoryType__Alternatives");
					put(grammarAccess.getValueAccess().getAlternatives(), "rule__Value__Alternatives");
					put(grammarAccess.getEnumDeclAccess().getAlternatives_2(), "rule__EnumDecl__Alternatives_2");
					put(grammarAccess.getDatatypeAccess().getAlternatives(), "rule__Datatype__Alternatives");
					put(grammarAccess.getInputValueAccess().getAlternatives(), "rule__InputValue__Alternatives");
					put(grammarAccess.getInputValueAccess().getAlternatives_0_0(), "rule__InputValue__Alternatives_0_0");
					put(grammarAccess.getInputOptionAccess().getAlternatives(), "rule__InputOption__Alternatives");
					put(grammarAccess.getInputOptionAccess().getAlternatives_0(), "rule__InputOption__Alternatives_0");
					put(grammarAccess.getInputOptionAccess().getAlternatives_4_0(), "rule__InputOption__Alternatives_4_0");
					put(grammarAccess.getFormfieldOptionAccess().getAlternatives(), "rule__FormfieldOption__Alternatives");
					put(grammarAccess.getInputtypeOptionAccess().getAlternatives(), "rule__InputtypeOption__Alternatives");
					put(grammarAccess.getOutfieldDeclAccess().getAlternatives(), "rule__OutfieldDecl__Alternatives");
					put(grammarAccess.getECLfieldTypeAccess().getAlternatives(), "rule__ECLfieldType__Alternatives");
					put(grammarAccess.getPosVizDataAccess().getAlternatives(), "rule__PosVizData__Alternatives");
					put(grammarAccess.getOutputOptionAccess().getAlternatives(), "rule__OutputOption__Alternatives");
					put(grammarAccess.getOutputOptionAccess().getAlternatives_0(), "rule__OutputOption__Alternatives_0");
					put(grammarAccess.getOutTypeAccess().getAlternatives_0(), "rule__OutType__Alternatives_0");
					put(grammarAccess.getOutputValueAccess().getAlternatives(), "rule__OutputValue__Alternatives");
					put(grammarAccess.getGenerateSectionAccess().getAlternatives(), "rule__GenerateSection__Alternatives");
					put(grammarAccess.getGenerateBodySaltAccess().getAlternatives_6(), "rule__GenerateBodySalt__Alternatives_6");
					put(grammarAccess.getVisualizationAccess().getAlternatives(), "rule__Visualization__Alternatives");
					put(grammarAccess.getVisualizationAccess().getAlternatives_0_0(), "rule__Visualization__Alternatives_0_0");
					put(grammarAccess.getFunctionAccess().getAlternatives(), "rule__Function__Alternatives");
					put(grammarAccess.getFunctionAccess().getAlternatives_2_2(), "rule__Function__Alternatives_2_2");
					put(grammarAccess.getFunctionAccess().getAlternatives_3_2(), "rule__Function__Alternatives_3_2");
					put(grammarAccess.getVisualOptionAccess().getAlternatives(), "rule__VisualOption__Alternatives");
					put(grammarAccess.getVisualOptionAccess().getAlternatives_0_0(), "rule__VisualOption__Alternatives_0_0");
					put(grammarAccess.getVisualMultivalAccess().getAlternatives(), "rule__VisualMultival__Alternatives");
					put(grammarAccess.getResourceOptionAccess().getAlternatives_0(), "rule__ResourceOption__Alternatives_0");
					put(grammarAccess.getProgramAccess().getGroup(), "rule__Program__Group__0");
					put(grammarAccess.getBasePropAccess().getGroup_0(), "rule__BaseProp__Group_0__0");
					put(grammarAccess.getBasePropAccess().getGroup_1(), "rule__BaseProp__Group_1__0");
					put(grammarAccess.getCategoryTypeListAccess().getGroup(), "rule__CategoryTypeList__Group__0");
					put(grammarAccess.getCategoryTypeListAccess().getGroup_1(), "rule__CategoryTypeList__Group_1__0");
					put(grammarAccess.getValueListAccess().getGroup(), "rule__ValueList__Group__0");
					put(grammarAccess.getValueListAccess().getGroup_1(), "rule__ValueList__Group_1__0");
					put(grammarAccess.getID_listAccess().getGroup(), "rule__ID_list__Group__0");
					put(grammarAccess.getID_listAccess().getGroup_1(), "rule__ID_list__Group_1__0");
					put(grammarAccess.getAssignAccess().getGroup(), "rule__Assign__Group__0");
					put(grammarAccess.getAssignListAccess().getGroup(), "rule__AssignList__Group__0");
					put(grammarAccess.getAssignListAccess().getGroup_1(), "rule__AssignList__Group_1__0");
					put(grammarAccess.getCompositionHeaderAccess().getGroup(), "rule__CompositionHeader__Group__0");
					put(grammarAccess.getContractInstanceAccess().getGroup(), "rule__ContractInstance__Group__0");
					put(grammarAccess.getContractInstanceAccess().getGroup_1(), "rule__ContractInstance__Group_1__0");
					put(grammarAccess.getFieldDeclAccess().getGroup(), "rule__FieldDecl__Group__0");
					put(grammarAccess.getEnumDeclAccess().getGroup(), "rule__EnumDecl__Group__0");
					put(grammarAccess.getInputSectionAccess().getGroup(), "rule__InputSection__Group__0");
					put(grammarAccess.getBoolAccess().getGroup(), "rule__Bool__Group__0");
					put(grammarAccess.getIntVarAccess().getGroup(), "rule__IntVar__Group__0");
					put(grammarAccess.getStringVarAccess().getGroup(), "rule__StringVar__Group__0");
					put(grammarAccess.getRecordAccess().getGroup(), "rule__Record__Group__0");
					put(grammarAccess.getDatasetAccess().getGroup(), "rule__Dataset__Group__0");
					put(grammarAccess.getGroupAccess().getGroup(), "rule__Group__Group__0");
					put(grammarAccess.getInputValueAccess().getGroup_0(), "rule__InputValue__Group_0__0");
					put(grammarAccess.getInputValueAccess().getGroup_1(), "rule__InputValue__Group_1__0");
					put(grammarAccess.getInputValueAccess().getGroup_2(), "rule__InputValue__Group_2__0");
					put(grammarAccess.getInputOptionsAccess().getGroup(), "rule__InputOptions__Group__0");
					put(grammarAccess.getInputOptionsAccess().getGroup_2(), "rule__InputOptions__Group_2__0");
					put(grammarAccess.getInputOptionAccess().getGroup_1(), "rule__InputOption__Group_1__0");
					put(grammarAccess.getInputOptionAccess().getGroup_2(), "rule__InputOption__Group_2__0");
					put(grammarAccess.getInputOptionAccess().getGroup_3(), "rule__InputOption__Group_3__0");
					put(grammarAccess.getInputOptionAccess().getGroup_4(), "rule__InputOption__Group_4__0");
					put(grammarAccess.getInputtypeOptionsAccess().getGroup(), "rule__InputtypeOptions__Group__0");
					put(grammarAccess.getInputtypeOptionsAccess().getGroup_1(), "rule__InputtypeOptions__Group_1__0");
					put(grammarAccess.getOutputSectionAccess().getGroup(), "rule__OutputSection__Group__0");
					put(grammarAccess.getECLIntegerAccess().getGroup(), "rule__ECLInteger__Group__0");
					put(grammarAccess.getECLUnsignedAccess().getGroup(), "rule__ECLUnsigned__Group__0");
					put(grammarAccess.getECLStringAccess().getGroup(), "rule__ECLString__Group__0");
					put(grammarAccess.getECLQstringAccess().getGroup(), "rule__ECLQstring__Group__0");
					put(grammarAccess.getECLVarstringAccess().getGroup(), "rule__ECLVarstring__Group__0");
					put(grammarAccess.getECLUnicodeAccess().getGroup(), "rule__ECLUnicode__Group__0");
					put(grammarAccess.getECLVarunicodeAccess().getGroup(), "rule__ECLVarunicode__Group__0");
					put(grammarAccess.getECLDataAccess().getGroup(), "rule__ECLData__Group__0");
					put(grammarAccess.getECLRealAccess().getGroup(), "rule__ECLReal__Group__0");
					put(grammarAccess.getECLOutputDeclAccess().getGroup(), "rule__ECLOutputDecl__Group__0");
					put(grammarAccess.getOutputOptionAccess().getGroup_1(), "rule__OutputOption__Group_1__0");
					put(grammarAccess.getOutputOptionAccess().getGroup_2(), "rule__OutputOption__Group_2__0");
					put(grammarAccess.getOutputOptionsAccess().getGroup(), "rule__OutputOptions__Group__0");
					put(grammarAccess.getOutputOptionsAccess().getGroup_2(), "rule__OutputOptions__Group_2__0");
					put(grammarAccess.getOutTypeAccess().getGroup(), "rule__OutType__Group__0");
					put(grammarAccess.getOutDatasetAccess().getGroup(), "rule__OutDataset__Group__0");
					put(grammarAccess.getOutputValueAccess().getGroup_0(), "rule__OutputValue__Group_0__0");
					put(grammarAccess.getOutputValueAccess().getGroup_1(), "rule__OutputValue__Group_1__0");
					put(grammarAccess.getOutputValueAccess().getGroup_2(), "rule__OutputValue__Group_2__0");
					put(grammarAccess.getOutputBaseAccess().getGroup(), "rule__OutputBase__Group__0");
					put(grammarAccess.getGenerateBodyInlineAccess().getGroup(), "rule__GenerateBodyInline__Group__0");
					put(grammarAccess.getGenerateBodySaltAccess().getGroup(), "rule__GenerateBodySalt__Group__0");
					put(grammarAccess.getVisualSectionAccess().getGroup(), "rule__VisualSection__Group__0");
					put(grammarAccess.getVisualizationAccess().getGroup_0(), "rule__Visualization__Group_0__0");
					put(grammarAccess.getVisualizationAccess().getGroup_1(), "rule__Visualization__Group_1__0");
					put(grammarAccess.getVisBasisAccess().getGroup(), "rule__VisBasis__Group__0");
					put(grammarAccess.getVisBasisQualifiersAccess().getGroup(), "rule__VisBasisQualifiers__Group__0");
					put(grammarAccess.getVisBasisQualifiersAccess().getGroup_2(), "rule__VisBasisQualifiers__Group_2__0");
					put(grammarAccess.getFunctionAccess().getGroup_2(), "rule__Function__Group_2__0");
					put(grammarAccess.getFunctionAccess().getGroup_3(), "rule__Function__Group_3__0");
					put(grammarAccess.getVisualSectionOptionsAccess().getGroup(), "rule__VisualSectionOptions__Group__0");
					put(grammarAccess.getVisualSectionOptionsAccess().getGroup_2(), "rule__VisualSectionOptions__Group_2__0");
					put(grammarAccess.getVisualSectionOptionAccess().getGroup(), "rule__VisualSectionOption__Group__0");
					put(grammarAccess.getVisualOptionsAccess().getGroup(), "rule__VisualOptions__Group__0");
					put(grammarAccess.getVisualOptionsAccess().getGroup_2(), "rule__VisualOptions__Group_2__0");
					put(grammarAccess.getVisualOptionAccess().getGroup_0(), "rule__VisualOption__Group_0__0");
					put(grammarAccess.getVisualOptionAccess().getGroup_1(), "rule__VisualOption__Group_1__0");
					put(grammarAccess.getVisualOptionAccess().getGroup_1_3(), "rule__VisualOption__Group_1_3__0");
					put(grammarAccess.getVisualOptionAccess().getGroup_2(), "rule__VisualOption__Group_2__0");
					put(grammarAccess.getCustomSectionAccess().getGroup(), "rule__CustomSection__Group__0");
					put(grammarAccess.getCustomValueAccess().getGroup(), "rule__CustomValue__Group__0");
					put(grammarAccess.getResourceOptionAccess().getGroup(), "rule__ResourceOption__Group__0");
					put(grammarAccess.getResourceOptionsAccess().getGroup(), "rule__ResourceOptions__Group__0");
					put(grammarAccess.getResourceOptionsAccess().getGroup_1(), "rule__ResourceOptions__Group_1__0");
					put(grammarAccess.getResourceValueAccess().getGroup(), "rule__ResourceValue__Group__0");
					put(grammarAccess.getResourceSectionAccess().getGroup(), "rule__ResourceSection__Group__0");
					put(grammarAccess.getProgramAccess().getComposition_headerAssignment_0(), "rule__Program__Composition_headerAssignment_0");
					put(grammarAccess.getProgramAccess().getBase_propsAssignment_1(), "rule__Program__Base_propsAssignment_1");
					put(grammarAccess.getProgramAccess().getContract_instancesAssignment_2(), "rule__Program__Contract_instancesAssignment_2");
					put(grammarAccess.getProgramAccess().getInput_sectionAssignment_3(), "rule__Program__Input_sectionAssignment_3");
					put(grammarAccess.getProgramAccess().getOutput_sectionAssignment_4(), "rule__Program__Output_sectionAssignment_4");
					put(grammarAccess.getProgramAccess().getVisual_sectionAssignment_5(), "rule__Program__Visual_sectionAssignment_5");
					put(grammarAccess.getProgramAccess().getGenerate_sectionAssignment_6(), "rule__Program__Generate_sectionAssignment_6");
					put(grammarAccess.getProgramAccess().getCustom_sectionAssignment_7(), "rule__Program__Custom_sectionAssignment_7");
					put(grammarAccess.getProgramAccess().getSesource_sectionAssignment_8(), "rule__Program__Sesource_sectionAssignment_8");
					put(grammarAccess.getBasePropAccess().getNameAssignment_0_0_0(), "rule__BaseProp__NameAssignment_0_0_0");
					put(grammarAccess.getBasePropAccess().getNameAssignment_0_0_1(), "rule__BaseProp__NameAssignment_0_0_1");
					put(grammarAccess.getBasePropAccess().getNameAssignment_0_0_2(), "rule__BaseProp__NameAssignment_0_0_2");
					put(grammarAccess.getBasePropAccess().getNameAssignment_0_0_3(), "rule__BaseProp__NameAssignment_0_0_3");
					put(grammarAccess.getBasePropAccess().getNameAssignment_0_0_4(), "rule__BaseProp__NameAssignment_0_0_4");
					put(grammarAccess.getBasePropAccess().getNameAssignment_0_0_5(), "rule__BaseProp__NameAssignment_0_0_5");
					put(grammarAccess.getBasePropAccess().getNameAssignment_0_0_6(), "rule__BaseProp__NameAssignment_0_0_6");
					put(grammarAccess.getBasePropAccess().getNameAssignment_0_0_7(), "rule__BaseProp__NameAssignment_0_0_7");
					put(grammarAccess.getBasePropAccess().getVal_listAssignment_0_1(), "rule__BaseProp__Val_listAssignment_0_1");
					put(grammarAccess.getBasePropAccess().getNameAssignment_1_0(), "rule__BaseProp__NameAssignment_1_0");
					put(grammarAccess.getBasePropAccess().getCat_listAssignment_1_1(), "rule__BaseProp__Cat_listAssignment_1_1");
					put(grammarAccess.getCategoryTypeListAccess().getCatsAssignment_0(), "rule__CategoryTypeList__CatsAssignment_0");
					put(grammarAccess.getCategoryTypeListAccess().getCatsAssignment_1_1(), "rule__CategoryTypeList__CatsAssignment_1_1");
					put(grammarAccess.getValueAccess().getNameAssignment_0(), "rule__Value__NameAssignment_0");
					put(grammarAccess.getValueAccess().getInt_valAssignment_1(), "rule__Value__Int_valAssignment_1");
					put(grammarAccess.getValueAccess().getStr_valAssignment_2(), "rule__Value__Str_valAssignment_2");
					put(grammarAccess.getValueListAccess().getValsAssignment_0(), "rule__ValueList__ValsAssignment_0");
					put(grammarAccess.getValueListAccess().getValsAssignment_1_1(), "rule__ValueList__ValsAssignment_1_1");
					put(grammarAccess.getAssignAccess().getNameAssignment_0(), "rule__Assign__NameAssignment_0");
					put(grammarAccess.getAssignAccess().getValsAssignment_2(), "rule__Assign__ValsAssignment_2");
					put(grammarAccess.getAssignListAccess().getAssignsAssignment_0(), "rule__AssignList__AssignsAssignment_0");
					put(grammarAccess.getAssignListAccess().getAssignsAssignment_1_1(), "rule__AssignList__AssignsAssignment_1_1");
					put(grammarAccess.getCompositionHeaderAccess().getNameAssignment_0(), "rule__CompositionHeader__NameAssignment_0");
					put(grammarAccess.getCompositionHeaderAccess().getAssignsAssignment_1(), "rule__CompositionHeader__AssignsAssignment_1");
					put(grammarAccess.getContractInstanceAccess().getSec_nameAssignment_0(), "rule__ContractInstance__Sec_nameAssignment_0");
					put(grammarAccess.getContractInstanceAccess().getValsAssignment_2(), "rule__ContractInstance__ValsAssignment_2");
					put(grammarAccess.getContractInstanceAccess().getVarsAssignment_4(), "rule__ContractInstance__VarsAssignment_4");
					put(grammarAccess.getContractInstanceAccess().getAssignsAssignment_6(), "rule__ContractInstance__AssignsAssignment_6");
					put(grammarAccess.getFieldDeclAccess().getNameAssignment_1(), "rule__FieldDecl__NameAssignment_1");
					put(grammarAccess.getFieldDeclAccess().getInput_opsAssignment_2(), "rule__FieldDecl__Input_opsAssignment_2");
					put(grammarAccess.getEnumDeclAccess().getEnum_decAssignment_0(), "rule__EnumDecl__Enum_decAssignment_0");
					put(grammarAccess.getEnumDeclAccess().getValsAssignment_2_0(), "rule__EnumDecl__ValsAssignment_2_0");
					put(grammarAccess.getEnumDeclAccess().getAssignsAssignment_2_1(), "rule__EnumDecl__AssignsAssignment_2_1");
					put(grammarAccess.getInputSectionAccess().getNameAssignment_0(), "rule__InputSection__NameAssignment_0");
					put(grammarAccess.getInputSectionAccess().getInputsAssignment_1(), "rule__InputSection__InputsAssignment_1");
					put(grammarAccess.getBoolAccess().getNameAssignment_1(), "rule__Bool__NameAssignment_1");
					put(grammarAccess.getIntVarAccess().getNameAssignment_1(), "rule__IntVar__NameAssignment_1");
					put(grammarAccess.getStringVarAccess().getNameAssignment_1(), "rule__StringVar__NameAssignment_1");
					put(grammarAccess.getRecordAccess().getNameAssignment_1(), "rule__Record__NameAssignment_1");
					put(grammarAccess.getDatasetAccess().getNameAssignment_1(), "rule__Dataset__NameAssignment_1");
					put(grammarAccess.getGroupAccess().getNameAssignment_1(), "rule__Group__NameAssignment_1");
					put(grammarAccess.getInputValueAccess().getInput_op_listAssignment_0_1(), "rule__InputValue__Input_op_listAssignment_0_1");
					put(grammarAccess.getInputValueAccess().getInput_op_listAssignment_1_1(), "rule__InputValue__Input_op_listAssignment_1_1");
					put(grammarAccess.getInputValueAccess().getFieldsAssignment_1_2(), "rule__InputValue__FieldsAssignment_1_2");
					put(grammarAccess.getInputValueAccess().getInput_op_listAssignment_2_1(), "rule__InputValue__Input_op_listAssignment_2_1");
					put(grammarAccess.getInputValueAccess().getValsAssignment_2_2(), "rule__InputValue__ValsAssignment_2_2");
					put(grammarAccess.getInputOptionsAccess().getInput_opsAssignment_1(), "rule__InputOptions__Input_opsAssignment_1");
					put(grammarAccess.getInputOptionsAccess().getInput_opsAssignment_2_1(), "rule__InputOptions__Input_opsAssignment_2_1");
					put(grammarAccess.getInputOptionAccess().getNameAssignment_0_0(), "rule__InputOption__NameAssignment_0_0");
					put(grammarAccess.getInputOptionAccess().getNameAssignment_0_1(), "rule__InputOption__NameAssignment_0_1");
					put(grammarAccess.getInputOptionAccess().getNameAssignment_0_2(), "rule__InputOption__NameAssignment_0_2");
					put(grammarAccess.getInputOptionAccess().getNameAssignment_0_3(), "rule__InputOption__NameAssignment_0_3");
					put(grammarAccess.getInputOptionAccess().getNameAssignment_0_4(), "rule__InputOption__NameAssignment_0_4");
					put(grammarAccess.getInputOptionAccess().getNameAssignment_0_5(), "rule__InputOption__NameAssignment_0_5");
					put(grammarAccess.getInputOptionAccess().getNameAssignment_1_0(), "rule__InputOption__NameAssignment_1_0");
					put(grammarAccess.getInputOptionAccess().getNameAssignment_2_0(), "rule__InputOption__NameAssignment_2_0");
					put(grammarAccess.getInputOptionAccess().getAssigns_listAssignment_2_2(), "rule__InputOption__Assigns_listAssignment_2_2");
					put(grammarAccess.getInputOptionAccess().getNameAssignment_3_0(), "rule__InputOption__NameAssignment_3_0");
					put(grammarAccess.getInputOptionAccess().getNameAssignment_4_0_0(), "rule__InputOption__NameAssignment_4_0_0");
					put(grammarAccess.getInputOptionAccess().getNameAssignment_4_0_1(), "rule__InputOption__NameAssignment_4_0_1");
					put(grammarAccess.getInputOptionAccess().getNameAssignment_4_0_2(), "rule__InputOption__NameAssignment_4_0_2");
					put(grammarAccess.getInputOptionAccess().getNameAssignment_4_0_3(), "rule__InputOption__NameAssignment_4_0_3");
					put(grammarAccess.getInputOptionAccess().getNameAssignment_4_0_4(), "rule__InputOption__NameAssignment_4_0_4");
					put(grammarAccess.getInputOptionAccess().getNameAssignment_4_0_5(), "rule__InputOption__NameAssignment_4_0_5");
					put(grammarAccess.getInputOptionAccess().getNameAssignment_4_0_6(), "rule__InputOption__NameAssignment_4_0_6");
					put(grammarAccess.getInputOptionAccess().getNameAssignment_4_0_7(), "rule__InputOption__NameAssignment_4_0_7");
					put(grammarAccess.getInputOptionAccess().getNameAssignment_4_0_8(), "rule__InputOption__NameAssignment_4_0_8");
					put(grammarAccess.getInputOptionAccess().getNameAssignment_4_0_9(), "rule__InputOption__NameAssignment_4_0_9");
					put(grammarAccess.getInputOptionAccess().getNameAssignment_4_0_10(), "rule__InputOption__NameAssignment_4_0_10");
					put(grammarAccess.getInputOptionAccess().getValsAssignment_4_2(), "rule__InputOption__ValsAssignment_4_2");
					put(grammarAccess.getOutputSectionAccess().getNameAssignment_0(), "rule__OutputSection__NameAssignment_0");
					put(grammarAccess.getOutputSectionAccess().getOutputsAssignment_1(), "rule__OutputSection__OutputsAssignment_1");
					put(grammarAccess.getOutfieldDeclAccess().getFieldsAssignment_3(), "rule__OutfieldDecl__FieldsAssignment_3");
					put(grammarAccess.getECLIntegerAccess().getNameAssignment_2(), "rule__ECLInteger__NameAssignment_2");
					put(grammarAccess.getECLUnsignedAccess().getNameAssignment_2(), "rule__ECLUnsigned__NameAssignment_2");
					put(grammarAccess.getECLStringAccess().getNameAssignment_2(), "rule__ECLString__NameAssignment_2");
					put(grammarAccess.getECLQstringAccess().getNameAssignment_2(), "rule__ECLQstring__NameAssignment_2");
					put(grammarAccess.getECLVarstringAccess().getNameAssignment_2(), "rule__ECLVarstring__NameAssignment_2");
					put(grammarAccess.getECLUnicodeAccess().getNameAssignment_2(), "rule__ECLUnicode__NameAssignment_2");
					put(grammarAccess.getECLVarunicodeAccess().getNameAssignment_2(), "rule__ECLVarunicode__NameAssignment_2");
					put(grammarAccess.getECLDataAccess().getNameAssignment_1(), "rule__ECLData__NameAssignment_1");
					put(grammarAccess.getECLRealAccess().getNameAssignment_1(), "rule__ECLReal__NameAssignment_1");
					put(grammarAccess.getECLOutputDeclAccess().getOptionsAssignment_1(), "rule__ECLOutputDecl__OptionsAssignment_1");
					put(grammarAccess.getOutputOptionAccess().getNameAssignment_0_0(), "rule__OutputOption__NameAssignment_0_0");
					put(grammarAccess.getOutputOptionAccess().getNameAssignment_0_1(), "rule__OutputOption__NameAssignment_0_1");
					put(grammarAccess.getOutputOptionAccess().getNameAssignment_0_2(), "rule__OutputOption__NameAssignment_0_2");
					put(grammarAccess.getOutputOptionAccess().getNameAssignment_0_3(), "rule__OutputOption__NameAssignment_0_3");
					put(grammarAccess.getOutputOptionAccess().getNameAssignment_0_4(), "rule__OutputOption__NameAssignment_0_4");
					put(grammarAccess.getOutputOptionAccess().getNameAssignment_1_0(), "rule__OutputOption__NameAssignment_1_0");
					put(grammarAccess.getOutputOptionAccess().getVarsAssignment_1_2(), "rule__OutputOption__VarsAssignment_1_2");
					put(grammarAccess.getOutputOptionAccess().getNameAssignment_2_0(), "rule__OutputOption__NameAssignment_2_0");
					put(grammarAccess.getOutputOptionAccess().getValsAssignment_2_2(), "rule__OutputOption__ValsAssignment_2_2");
					put(grammarAccess.getOutputOptionsAccess().getOutput_opsAssignment_1(), "rule__OutputOptions__Output_opsAssignment_1");
					put(grammarAccess.getOutputOptionsAccess().getOutput_opsAssignment_2_1(), "rule__OutputOptions__Output_opsAssignment_2_1");
					put(grammarAccess.getOutTypeAccess().getValAssignment_1(), "rule__OutType__ValAssignment_1");
					put(grammarAccess.getOutDatasetAccess().getNameAssignment_1(), "rule__OutDataset__NameAssignment_1");
					put(grammarAccess.getOutDatasetAccess().getOut_baseAssignment_2(), "rule__OutDataset__Out_baseAssignment_2");
					put(grammarAccess.getOutDatasetAccess().getOpsAssignment_3(), "rule__OutDataset__OpsAssignment_3");
					put(grammarAccess.getOutputValueAccess().getOpsAssignment_0_1(), "rule__OutputValue__OpsAssignment_0_1");
					put(grammarAccess.getOutputValueAccess().getEcl_varsAssignment_1_1(), "rule__OutputValue__Ecl_varsAssignment_1_1");
					put(grammarAccess.getOutputBaseAccess().getBaseAssignment_1(), "rule__OutputBase__BaseAssignment_1");
					put(grammarAccess.getGenerateBodyInlineAccess().getNameAssignment_0(), "rule__GenerateBodyInline__NameAssignment_0");
					put(grammarAccess.getGenerateBodySaltAccess().getNameAssignment_0(), "rule__GenerateBodySalt__NameAssignment_0");
					put(grammarAccess.getVisualSectionAccess().getSec_nameAssignment_0(), "rule__VisualSection__Sec_nameAssignment_0");
					put(grammarAccess.getVisualSectionAccess().getVis_opsAssignment_2(), "rule__VisualSection__Vis_opsAssignment_2");
					put(grammarAccess.getVisualSectionAccess().getVis_elementsAssignment_3(), "rule__VisualSection__Vis_elementsAssignment_3");
					put(grammarAccess.getVisualizationAccess().getNameAssignment_0_1(), "rule__Visualization__NameAssignment_0_1");
					put(grammarAccess.getVisualizationAccess().getInputAssignment_0_3(), "rule__Visualization__InputAssignment_0_3");
					put(grammarAccess.getVisualizationAccess().getVis_opAssignment_0_5(), "rule__Visualization__Vis_opAssignment_0_5");
					put(grammarAccess.getVisualizationAccess().getNameAssignment_1_1(), "rule__Visualization__NameAssignment_1_1");
					put(grammarAccess.getVisualizationAccess().getVis_opAssignment_1_2(), "rule__Visualization__Vis_opAssignment_1_2");
					put(grammarAccess.getVisBasisAccess().getBasisAssignment_0(), "rule__VisBasis__BasisAssignment_0");
					put(grammarAccess.getVisBasisAccess().getQualsAssignment_1(), "rule__VisBasis__QualsAssignment_1");
					put(grammarAccess.getVisBasisQualifiersAccess().getFuncsAssignment_1(), "rule__VisBasisQualifiers__FuncsAssignment_1");
					put(grammarAccess.getVisBasisQualifiersAccess().getFuncsAssignment_2_1(), "rule__VisBasisQualifiers__FuncsAssignment_2_1");
					put(grammarAccess.getFunctionAccess().getVarsAssignment_0(), "rule__Function__VarsAssignment_0");
					put(grammarAccess.getFunctionAccess().getValsAssignment_1(), "rule__Function__ValsAssignment_1");
					put(grammarAccess.getFunctionAccess().getVarsAssignment_2_2_0(), "rule__Function__VarsAssignment_2_2_0");
					put(grammarAccess.getFunctionAccess().getValsAssignment_2_2_1(), "rule__Function__ValsAssignment_2_2_1");
					put(grammarAccess.getFunctionAccess().getVarsAssignment_3_2_0(), "rule__Function__VarsAssignment_3_2_0");
					put(grammarAccess.getFunctionAccess().getValsAssignment_3_2_1(), "rule__Function__ValsAssignment_3_2_1");
					put(grammarAccess.getVisualSectionOptionsAccess().getVis_opsAssignment_1(), "rule__VisualSectionOptions__Vis_opsAssignment_1");
					put(grammarAccess.getVisualSectionOptionsAccess().getVis_opsAssignment_2_1(), "rule__VisualSectionOptions__Vis_opsAssignment_2_1");
					put(grammarAccess.getVisualSectionOptionAccess().getNameAssignment_0(), "rule__VisualSectionOption__NameAssignment_0");
					put(grammarAccess.getVisualSectionOptionAccess().getValsAssignment_2(), "rule__VisualSectionOption__ValsAssignment_2");
					put(grammarAccess.getVisualOptionsAccess().getVis_opsAssignment_1(), "rule__VisualOptions__Vis_opsAssignment_1");
					put(grammarAccess.getVisualOptionsAccess().getVis_opsAssignment_2_1(), "rule__VisualOptions__Vis_opsAssignment_2_1");
					put(grammarAccess.getVisualOptionAccess().getNameAssignment_0_0_0(), "rule__VisualOption__NameAssignment_0_0_0");
					put(grammarAccess.getVisualOptionAccess().getNameAssignment_0_0_1(), "rule__VisualOption__NameAssignment_0_0_1");
					put(grammarAccess.getVisualOptionAccess().getNameAssignment_0_0_2(), "rule__VisualOption__NameAssignment_0_0_2");
					put(grammarAccess.getVisualOptionAccess().getNameAssignment_0_0_3(), "rule__VisualOption__NameAssignment_0_0_3");
					put(grammarAccess.getVisualOptionAccess().getNameAssignment_0_0_4(), "rule__VisualOption__NameAssignment_0_0_4");
					put(grammarAccess.getVisualOptionAccess().getNameAssignment_0_0_5(), "rule__VisualOption__NameAssignment_0_0_5");
					put(grammarAccess.getVisualOptionAccess().getNameAssignment_0_0_6(), "rule__VisualOption__NameAssignment_0_0_6");
					put(grammarAccess.getVisualOptionAccess().getNameAssignment_0_0_7(), "rule__VisualOption__NameAssignment_0_0_7");
					put(grammarAccess.getVisualOptionAccess().getFuncsAssignment_0_2(), "rule__VisualOption__FuncsAssignment_0_2");
					put(grammarAccess.getVisualOptionAccess().getVis_multAssignment_1_0(), "rule__VisualOption__Vis_multAssignment_1_0");
					put(grammarAccess.getVisualOptionAccess().getFuncsAssignment_1_2(), "rule__VisualOption__FuncsAssignment_1_2");
					put(grammarAccess.getVisualOptionAccess().getFuncsAssignment_1_3_1(), "rule__VisualOption__FuncsAssignment_1_3_1");
					put(grammarAccess.getVisualOptionAccess().getNameAssignment_2_0(), "rule__VisualOption__NameAssignment_2_0");
					put(grammarAccess.getVisualMultivalAccess().getNameAssignment_0(), "rule__VisualMultival__NameAssignment_0");
					put(grammarAccess.getVisualMultivalAccess().getNameAssignment_1(), "rule__VisualMultival__NameAssignment_1");
					put(grammarAccess.getVisualMultivalAccess().getNameAssignment_2(), "rule__VisualMultival__NameAssignment_2");
					put(grammarAccess.getVisualMultivalAccess().getNameAssignment_3(), "rule__VisualMultival__NameAssignment_3");
					put(grammarAccess.getVisualMultivalAccess().getNameAssignment_4(), "rule__VisualMultival__NameAssignment_4");
					put(grammarAccess.getVisualMultivalAccess().getNameAssignment_5(), "rule__VisualMultival__NameAssignment_5");
					put(grammarAccess.getVisualMultivalAccess().getNameAssignment_6(), "rule__VisualMultival__NameAssignment_6");
					put(grammarAccess.getCustomSectionAccess().getNameAssignment_0(), "rule__CustomSection__NameAssignment_0");
					put(grammarAccess.getCustomSectionAccess().getCust_valsAssignment_1(), "rule__CustomSection__Cust_valsAssignment_1");
					put(grammarAccess.getResourceOptionAccess().getNameAssignment_0_0(), "rule__ResourceOption__NameAssignment_0_0");
					put(grammarAccess.getResourceOptionAccess().getNameAssignment_0_1(), "rule__ResourceOption__NameAssignment_0_1");
					put(grammarAccess.getResourceOptionAccess().getNameAssignment_0_2(), "rule__ResourceOption__NameAssignment_0_2");
					put(grammarAccess.getResourceOptionAccess().getNameAssignment_0_3(), "rule__ResourceOption__NameAssignment_0_3");
					put(grammarAccess.getResourceOptionAccess().getValsAssignment_2(), "rule__ResourceOption__ValsAssignment_2");
					put(grammarAccess.getResourceOptionsAccess().getRes_opsAssignment_0(), "rule__ResourceOptions__Res_opsAssignment_0");
					put(grammarAccess.getResourceOptionsAccess().getRes_opsAssignment_1_1(), "rule__ResourceOptions__Res_opsAssignment_1_1");
					put(grammarAccess.getResourceValueAccess().getRes_opsAssignment_2(), "rule__ResourceValue__Res_opsAssignment_2");
					put(grammarAccess.getResourceSectionAccess().getNameAssignment_0(), "rule__ResourceSection__NameAssignment_0");
					put(grammarAccess.getResourceSectionAccess().getRes_valsAssignment_1(), "rule__ResourceSection__Res_valsAssignment_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.xtext.hipie.ui.contentassist.antlr.internal.InternalHIPIEParser typedParser = (org.xtext.hipie.ui.contentassist.antlr.internal.InternalHIPIEParser) parser;
			typedParser.entryRuleProgram();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public HIPIEGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(HIPIEGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
